# Background & foreground
background              #0D1116
foreground              #b7bfce

# Cursor
cursor                  #ffffff
cursor_text_color       #0D1116

# Selection
selection_background    #3d2a5e
selection_foreground    #e9b3fd

# URL underline
url_color               #04d1f9

# Window border
active_border_color     #987afb
inactive_border_color   #232e3b
bell_border_color       #e58f2a

# Tab bar
active_tab_background   #987afb
active_tab_foreground   #0D1116
inactive_tab_background #141b22
inactive_tab_foreground #b7bfce

# Black
color0                  #0D1116
color8                  #232e3b

# Red
color1                  #f16c75
color9                  #f16c75

# Green
color2                  #37f499
color10                 #37f499

# Yellow
color3                  #f1fc79
color11                 #f1fc79

# Blue
color4                  #987afb
color12                 #987afb

# Magenta
color5                  #fca6ff
color13                 #f94dff

# Cyan
color6                  #04d1f9
color14                 #04d1f9

# White
color7                  #b7bfce
color15                 #ffffff
