background            #a8a8a8
foreground            #1a1a1a
selection_background  #9b8d7f
selection_foreground  #a8a8a8
cursor                #ffffff
cursor_text_color     #a8a8a8
cursor_opacity        0.7
url_color             #4d7878

# black
color0  #909090
color8  #787878

# red
color1  #a32828
color9  #4d7878

# green
color2  #8a7d70
color10 #8a7d70

# yellow
color3  #7d7060
color11 #7d7060

# blue
color4  #707070
color12 #707070

# purple
color5  #808080
color13 #808080

# cyan
color6  #909090
color14 #909090

# white
color7  #1e1e1e
color15 #444444
